version: '3'

volumes:
    alt_home:

services:
    spack-cmr-built-service:
        privileged: true
        build:
            context: .
            dockerfile: cmr.dockerfile
        image: stevenrbrandt/spack-cmr-built
        entrypoint: sleep infinity
        container_name: alt2
        volumes:
            - alt_home:/home

